import type { Metadata } from 'next';
import './../styles/globals.css';
import { alfaSlabOne, montserrat } from '@/styles/fonts';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${alfaSlabOne.variable}`}>
				{children}
			</body>
		</html>
	);
};

export default RootLayout;
