import type { Metadata } from 'next';
import { Montserrat, Alfa_Slab_One } from 'next/font/google';
import './../styles/globals.css';

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
});

const alfaSlabOne = Alfa_Slab_One({
	variable: '--font-alfa-slab-one',
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable} ${alfaSlabOne.variable}`}>
				{children}
			</body>
		</html>
	);
}
